### ISSUE TITLE
Bug faced in Single Player mode - Unable to see plane unless damaged by AI

### ISSUE THREAD

**Issue by bryankwe** [boredcoco/rollite#17]
![image](https://user-images.githubusercontent.com/97665622/180917648-10c9f813-e7b5-48dd-a8ae-73d76cd4c210.png)

Found a bug where the plane disappears from screen view (although still active in scene because the AI is moving around). Only able to see the plane upon being damaged (the white flash is shown), but after that the plane cannot be seen again. Unsure why this happens and did not notice what happened before that (because it was my first playthrough). I have not been able to reproduce this bug in subsequent playthroughs.

Congratulations on completing Rollite!

**Comment by boredcoco** [comment]
The issue has been resolved! We would appreciate it if you could check it out and let us know if you face any further issues! By the way, congrats on finishing FarmDemAnimals, it looks amazing!
